name: Generate Screenshot

on:
  push:
    branches:
      - main
 
jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code using PAT
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start development server in the background
        run: |
          npm start &
          sleep 60  # Give it a minute to start up.

      - name: Set up Git with PAT authentication
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://${{secrets.GH_PAT}}@github.com/Revc0/Screenshot_pipeline.git
      
      - name: Capture screenshot
        run: node screenshot.js

      - name: Commit and push screenshot using git-auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update screenshot"
          commit_options: "--no-verify"
          repository: .
          file_pattern: screenshot.png
          push_options: "--force"
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"

      # Optional: Kill the server
      - name: Kill development server
        run: pkill node
