name: Generate Screenshot

on:
  push:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start development server in the background
        run: |
          npm start &
          sleep 60  # Give it a minute to start up.

      - name: Capture screenshot
        run: node screenshot.js

      - name: Commit and push screenshot
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add screenshot.png
          git commit -m "Update screenshot" || echo "No changes to commit"
          git push https://${{secrets.GH_PAT}}@github.com/${{github.repository}} HEAD:main

      # Optional: Kill the server
      - name: Kill development server
        run: pkill node
