name: Generate Screenshot

on:
  push:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Capture screenshot
        run: node screenshot.js

      - name: Commit and push screenshot
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add screenshot.png
          git commit -m "Update screenshot" || echo "No changes to commit"
          git push
